# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainUI(object):
    def setupUi(self, mainUI):
        mainUI.setObjectName("mainUI")
        mainUI.setWindowModality(QtCore.Qt.NonModal)
        mainUI.resize(1280, 720)
        # mainUI.setSizeGripEnabled(False)
        self.tabWidget = QtWidgets.QTabWidget(mainUI)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1240, 720))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(1100, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(290, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setGeometry(QtCore.QRect(790, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.productSearchBtn = QtWidgets.QPushButton(self.tab_1)
        self.productSearchBtn.setGeometry(QtCore.QRect(830, 10, 80, 40))
        self.productSearchBtn.setAutoDefault(True)
        self.productSearchBtn.setObjectName("productSearchBtn")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(540, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listWidget1 = QtWidgets.QListWidget(self.tab_1)
        self.listWidget1.setGeometry(QtCore.QRect(20, 91, 1200, 541))
        self.listWidget1.setObjectName("listWidget1")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setGeometry(QtCore.QRect(50, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.productLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.productLineEdit.setGeometry(QtCore.QRect(30, 10, 780, 40))
        self.productLineEdit.setMaxLength(1024)
        self.productLineEdit.setObjectName("productLineEdit")
        self.productOutPutBtn = QtWidgets.QPushButton(self.tab_1)
        self.productOutPutBtn.setGeometry(QtCore.QRect(1130, 10, 80, 40))
        self.productOutPutBtn.setAutoDefault(True)
        self.productOutPutBtn.setObjectName("productOutPutBtn")
        self.productPreBtn = QtWidgets.QPushButton(self.tab_1)
        self.productPreBtn.setGeometry(QtCore.QRect(330, 640, 93, 34))
        self.productPreBtn.setObjectName("productPreBtn")
        self.productTotalPageLab = QtWidgets.QLabel(self.tab_1)
        self.productTotalPageLab.setGeometry(QtCore.QRect(730, 650, 100, 15))
        self.productTotalPageLab.setObjectName("productTotalPageLab")
        self.productNextBtn = QtWidgets.QPushButton(self.tab_1)
        self.productNextBtn.setGeometry(QtCore.QRect(460, 640, 93, 34))
        self.productNextBtn.setObjectName("productNextBtn")
        self.productGoBtn = QtWidgets.QPushButton(self.tab_1)
        self.productGoBtn.setGeometry(QtCore.QRect(660, 640, 51, 34))
        self.productGoBtn.setObjectName("productGoBtn")
        self.productPageLineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.productPageLineEdit.setGeometry(QtCore.QRect(590, 640, 60, 30))
        self.productPageLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.productPageLineEdit.setMaxLength(5)
        self.productPageLineEdit.setObjectName("productPageLineEdit")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.siteSearchBtn = QtWidgets.QPushButton(self.tab_2)
        self.siteSearchBtn.setGeometry(QtCore.QRect(830, 10, 80, 40))
        self.siteSearchBtn.setAutoDefault(True)
        self.siteSearchBtn.setObjectName("siteSearchBtn")
        self.listWidget2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget2.setGeometry(QtCore.QRect(20, 91, 1200, 541))
        self.listWidget2.setObjectName("listWidget2")
        self.sitePreBtn = QtWidgets.QPushButton(self.tab_2)
        self.sitePreBtn.setGeometry(QtCore.QRect(330, 640, 93, 34))
        self.sitePreBtn.setObjectName("sitePreBtn")
        self.siteNextBtn = QtWidgets.QPushButton(self.tab_2)
        self.siteNextBtn.setGeometry(QtCore.QRect(460, 640, 93, 34))
        self.siteNextBtn.setObjectName("siteNextBtn")
        self.siteGoBtn = QtWidgets.QPushButton(self.tab_2)
        self.siteGoBtn.setGeometry(QtCore.QRect(660, 640, 51, 34))
        self.siteGoBtn.setObjectName("siteGoBtn")
        self.siteTotalPageLab = QtWidgets.QLabel(self.tab_2)
        self.siteTotalPageLab.setGeometry(QtCore.QRect(730, 650, 100, 15))
        self.siteTotalPageLab.setObjectName("siteTotalPageLab")
        self.sitePageLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.sitePageLineEdit.setGeometry(QtCore.QRect(590, 640, 60, 30))
        self.sitePageLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.sitePageLineEdit.setMaxLength(5)
        self.sitePageLineEdit.setObjectName("sitePageLineEdit")
        self.siteLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.siteLineEdit.setGeometry(QtCore.QRect(30, 10, 780, 40))
        self.siteLineEdit.setMaxLength(1024)
        self.siteLineEdit.setObjectName("siteLineEdit")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(290, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(790, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(540, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(1100, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(50, 60, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.siteOutPutBtn = QtWidgets.QPushButton(self.tab_2)
        self.siteOutPutBtn.setGeometry(QtCore.QRect(1130, 10, 80, 40))
        self.siteOutPutBtn.setAutoDefault(True)
        self.siteOutPutBtn.setObjectName("siteOutPutBtn")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(mainUI)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainUI)

    def retranslateUi(self, mainUI):
        _translate = QtCore.QCoreApplication.translate
        mainUI.setWindowTitle(_translate("mainUI", "国际站辅助"))
        self.label_5.setText(_translate("mainUI", "图片"))
        self.label_2.setText(_translate("mainUI", "价格"))
        self.label_4.setText(_translate("mainUI", "关键字"))
        self.productSearchBtn.setText(_translate("mainUI", "搜索"))
        self.label_3.setText(_translate("mainUI", "站点"))
        self.label.setText(_translate("mainUI", "商品名称"))
        self.productLineEdit.setPlaceholderText(_translate("mainUI", "搜索商品名称"))
        self.productOutPutBtn.setText(_translate("mainUI", "导出"))
        self.productPreBtn.setText(_translate("mainUI", "上一页"))
        self.productTotalPageLab.setText(_translate("mainUI", "共x页"))
        self.productNextBtn.setText(_translate("mainUI", "下一页"))
        self.productGoBtn.setText(_translate("mainUI", "go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("mainUI", "搜索商品"))
        self.siteSearchBtn.setText(_translate("mainUI", "搜索"))
        self.sitePreBtn.setText(_translate("mainUI", "上一页"))
        self.siteNextBtn.setText(_translate("mainUI", "下一页"))
        self.siteGoBtn.setText(_translate("mainUI", "go"))
        self.siteTotalPageLab.setText(_translate("mainUI", "共x页"))
        self.siteLineEdit.setPlaceholderText(_translate("mainUI", "搜索站点地址"))
        self.label_6.setText(_translate("mainUI", "价格"))
        self.label_7.setText(_translate("mainUI", "关键字"))
        self.label_8.setText(_translate("mainUI", "站点"))
        self.label_9.setText(_translate("mainUI", "图片"))
        self.label_10.setText(_translate("mainUI", "商品名称"))
        self.siteOutPutBtn.setText(_translate("mainUI", "导出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainUI", "搜索商家"))

